version: '3.1'

services: 
  postgres:
    image: postgres:12.1-alpine
    container_name: advpgsql
    environment: 
      # POSTGRES_DB: dailystardb
      # POSTGRES_USER: dailystaruser
      POSTGRES_PASSWORD: admin
    volumes: 
      - ./pddata:/var/lib/postgresql/data
    ports:
      - 9432:5432  
  pgadmin:
    image: dpage/pgadmin4:4.16
    container_name: advpgadmin
    environment: 
    - PGADMIN_DEFAULT_EMAIL=satcom@satcombd.com
    - PGADMIN_DEFAULT_PASSWORD=admin
    volumes: 
    - ./localconnection.json:/pgadmin4/servers.json
    ports:
    - 9080:80